base_url = "https://shahnewaz-labib.github.io"
title = "shahnewaz-labib"
build_search_index = true
generate_feeds = true
minify_html = true

theme = "apollo"
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "ayu-light"
mathjax = true
mathjax_dollar_inline_enable = true

[extra]
use_cdn = false
theme = "toggle"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/tags", url = "/tags", weight = 2 },
    # { name = "/projects", url = "/projects", weight = 3 },
    # { name = "/talks", url= "/talks", weight= 4 },
    { name = "/about", url = "/about", weight = 5 },
]

socials = [
    { name = "github", url = "https://github.com/shahnewaz-labib/", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/shahnewaz-labib", icon = "linkedin" },
]
