name: Zola

on:
  push:
    branches: [main]
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Stash changes
        run: |
          git stash
  
      - name: Checkout gh-pages branch
        run: |
          git fetch origin
          git checkout gh-pages
  
      - name: Apply stash
        run: |
          git stash pop
  
      - name: Ensure CNAME file
        run: |
          echo 'blog.shahnewazlabib.com' > CNAME
          git add CNAME
          git commit -m "Add CNAME file"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
